name: Hello World
on: [push]

jobs:
  hello-job:
     runs-on: ubuntu-latest
     steps:
       - name: Echo Text
         run: echo Hello, world!
       - name: Display secret
         env: 
           super_secret: ${{secrets.SUPERSECRET}} 
         run: echo $super_secret
